### ISSUE TITLE
Unable to insert characters at beginning of line when mode=character and indentation type is tabs

### ISSUE THREAD

**Issue by jgkamat** [DarthFennec/highlight-indent-guides#20]
High! I first want to thank you for making this plugin, it's the best I've used so far!

For me, when I insert characters at the start (after whitespace, before text), when indenting with tabs (and a tab size of 4), and `(setq
highlight-indent-guides-method 'character)` set, I cannot insert text. By 'cannot', I mean I can insert text, but the cursor dosen't move, and the text is hidden. Turning off hl-indent-guides shows the text once more. Here's a few screenshots to show what I mean:

Before inserting any text (point is at correct place)
![2017-04-20-171101_126x105_scrot](https://cloud.githubusercontent.com/assets/4349709/25252934/e1ecc570-25ec-11e7-8f22-bfbadeb2bfa0.png)

After inserting text, (and copying the current line into a comment after the line):
![2017-04-20-171156_417x101_scrot](https://cloud.githubusercontent.com/assets/4349709/25252944/ee0aaafc-25ec-11e7-9c76-7643f875df5a.png)

I've tested this on a blank emacs config (see above), setting the mode to char, setting `indent-tabs-mode` to `t`, and setting `tab-width` to 4. in `python-mode`

I can't reproduce this on a tab-width of 8, or when using spaces (or when using the default highlight mode), so it's probably a problem with assuming tab size is 8 when it should be `tab-width`. Let me know if you can't reproduce or if you need any more information!

**Comment by jgkamat** [comment]
One more peice of information, when I put two spaces at the start of a line, I can see a new guide where the text used to be and I can enter in text normally: 
![2017-04-20-173842_458x98_scrot](https://cloud.githubusercontent.com/assets/4349709/25253751/3606c4aa-25f0-11e7-84d1-ce6822ebb8b2.png)

**Comment by DarthFennec** [comment]
I see ... I don't use tabs for indentation very often, so I've never encountered this before.

I do seem to be able to reproduce this, although for me it also happens when I use a `tab-width` of 8 in `go-mode`. The first seven characters I type are invisible, and the rest show up ... unless the first character is a space, in which case everything shows up normally. You seem to be seeing the same thing; in your screenshot, you have a `tab-width` of four, and the first three characters are hidden.

I think I know what's going on. I display guides in tab characters using the `display` text property: a character with a `display` property set to a string will appear to be replaced with that string when rendered. So, to add a guide to a 4-width tab, I set the tab's `display` property to the string <code>"|&nbsp;&nbsp;&nbsp;"</code> (a pipe followed by three spaces). This has the same width as a 4-width tab, so it behaves as if I'm just drawing the guide on top of the tab.

If multiple consecutive characters have the same `display` string, they will be replaced as a group, rather than individually. So a string "aaaaa" where each 'a' had a `display` of "z" would show up as just "z", rather than "zzzzz". This is a great feature, but I don't use it here.

I believe the issue is this: by default, when you type a new character, it inherits the text properties of the character before it. If it inherits the `display` property, the character you just typed now has the same `display` as the one next to it. Because of the grouping rule, they're replaced together, and this causes the new character to appear invisible.

The confusing thing about this is, there's a special variable called `text-property-default-nonsticky`, which lists properties that don't inherit from surrounding text, and `display` is in that list. Although ... I think what's happening is, the property I use to cache guide information, `highlight-indent-guides-prop`, is still inheriting. So, `font-lock` sees this inherited property and adds `display` properties accordingly. That might be it. Taking a look ...

Yeah I think that was it. I'm getting normal behavior now, anyway. Just pushed a fix, let me know if it helps. Thanks!

**Comment by jgkamat** [comment]
Wow, thanks for the quick fix! I don't know too much about emacs display settings (so I don't really understand how this fixed it), but everything is working fine for me now, thanks so much! 

I'll probably go through the source at some point to learn more about how everything works :P 

I'll close this for now, since it's fixed. Thanks again! :smile:

**Comment by DarthFennec** [comment]
Cool, glad that fixed it! Let me know if you have any more trouble.
