### ISSUE TITLE
Problem with web-mode 

### ISSUE THREAD

**Issue by praveenperera** [DarthFennec/highlight-indent-guides#22]
The automatic color of the character mode does not seem to work with web-mode, it does not seem to change the luminosity. See examples below.

File with web-mode:

http://i.imgur.com/D0OZZVM.png

Same file in html-mode:

http://i.imgur.com/UhnneDo.png

**Comment by DarthFennec** [comment]
I am able to reproduce this. It looks like it's not the automatic color setup, because even when I set the colors manually they still get reset in `web-mode` for me.

I found [this issue](https://github.com/fxbois/web-mode/issues/566), which fixes the color problem. However, I noticed a different issue with `web-mode`, which is that modifying indentation appears to leave extra unhighlighted guides behind in the wrong places. This really shouldn't happen.

After looking into the `web-mode` source, this second problem appears to be happening because `web-mode` overrides the default `font-lock-unfontify-region-function`, which is in charge of removing old guides. It replaces this function with an empty function that doesn't do anything.

I've fixed the color bug and pushed an update. As for the other problem, I've created an issue [here](https://github.com/fxbois/web-mode/issues/879). In the meantime, you can fix it with something like the following:

```emacs-lisp
(require 'web-mode)
(defun my-unfontify-function (beg end)
  (remove-list-of-text-properties beg end '(display)))
(defun my-register-unfontify ()
  (setq font-lock-unfontify-region-function 'my-unfontify-function))
(add-hook 'web-mode-hook 'my-register-unfontify t)
```

Hope this helps.

**Comment by praveenperera** [comment]
Awesome! I'm using spacemacs and seems like the package hasn't updated yet in melpa so I made the change in the file manually and added the code snippet above to my .spacemacs file. And it works perfectly now!! Thanks for getting to this so quickly and for the great package.

I can also now toggle the the indent guides on and off in web-mode, whereas before I couldn't.

Thanks again 🎉 🎉  🎉
