### ISSUE TITLE
highlight-indent-guides breaks set-text-properties, even when disabled

### ISSUE THREAD

**Issue by thblt** [DarthFennec/highlight-indent-guides#23]
Steps to reproduce
----- 

From Emacs -Q, open a buffer with these two sexps, and evaluate them:

```
(save-excursion
  (goto-char (point-min))
  (set-text-properties (point-min) (line-end-position)
		       `(display "abcdef")
		       ))

(save-excursion
  (goto-char (point-min))
  (set-text-properties (point-min) (line-end-position)
		       nil))
```

The first line gets converted to abcded, then back to itself.  
With `M-x highlight-indent-guides-mode`, these sexps stop working. 
 
But even when disabling `M-x highlight-indent-guides-mode`, they will never work again.

This is a severe issue, because it breaks the password hiding feature of @NicolasPetton's [pass](/NicolasPetton/pass) major mode for [password-store](https://www.passwordstore.org/)

Thanks!
Thibault

**Comment by DarthFennec** [comment]
As stated in the project's [`README.md`](https://github.com/DarthFennec/highlight-indent-guides/blob/master/README.md) file, `highlight-indent-guides` cannot work correctly unless it manages the `display` property via `font-lock`. However, when it does manage this property, `font-lock` will automatically clear all other uses of `display` from the buffer. This is a known issue, with no good solution that I know of. I feel like it's generally acceptable for the time being, because nearly every other mode that uses `display` uses it in the context of an overlay, and overlays aren't affected by this problem.

As discussed in issue #8, at the moment I don't bother unmanaging `display` when `highlight-indent-guides` gets disabled. This is because if I do remove it from the list, `font-lock` can no longer delete leftover `display` properties, so there are just a bunch of extra guide artifacts all over the buffer now. Oddly, this still happens even if I wait to remove it from the list until after I redraw the buffer. I feel like this issue will probably be easier to solve than the other one, but as of right now, nothing I've tried has worked. I will continue to look into it, though.

In the meantime, I suggest simply not using `highlight-indent-guides` in `pass-mode` at all. If you never enable the mode, it shouldn't affect the buffer, so `display` should still work.

I hope that's helpful. Thanks for the issue.

**Comment by thblt** [comment]
Thanks for the detailed reply!  There's something I'm still not sure I understand.  I enable h-i-g with a hook on `prog-mode`:

```
  (use-package highlight-indent-guides
    :init (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
    :config (setq highlight-indent-guides-method 'character
                  highlight-indent-guides-character ?┃
                  highlight-indent-guides-auto-character-face-perc 25))
```

I then assume its (side-)effects should be limited to prog-mode and modes inheriting from it.  But [Pass' view mode derives no mode](https://github.com/NicolasPetton/pass/blob/master/pass.el#L350), and pass-view buffers seem to start with h-i-g disabled (ie `M-x highlight-indent-guides-mode RET` displays "Highlight-Indent-Guides mode enabled in current buffer", and there's no indent marks in the buffer).  So I don't really understand how the bug can happen, and how to fix it.

Thanks!

**Comment by DarthFennec** [comment]
How strange. That doesn't happen for me, everything works fine ... Try opening a Pass view buffer and typing <kbd>C-h v font-lock-extra-managed-props RET</kbd>, and let me know what it says.

**Comment by thblt** [comment]
My mistake, I can't reproduce the issue from `emacs -q` with this setup.  I'll try to narrow it down further and let you know if it's in any way  related to h-i-g.

**Comment by thblt** [comment]
Please ignore the previous message, I've found a way to reproduce.

Starting from `emacs -Q`, evaluate this in the scratch buffer:

```
(require 'pass)
(require 'highlight-indent-guides)

(use-package highlight-indent-guides
  :init (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
  :config (setq highlight-indent-guides-method 'character
		highlight-indent-guides-character ?┃
		highlight-indent-guides-auto-character-face-perc 25))
```

Play with pass, the password is correctly hidden.

Now back on the scratch buffer, do `M-x emacs-lisp-mode RET` (this won't change the major mode, but will restart it, activating the h-i-g hook).  This is important.  At this point, password hiding ceases to work in new *and* existing pass-view buffers (already hidden passwords remain hidden, but `C-c C-c` makes them forever visible)  

----- 

>  Try opening a Pass view buffer and typing `C-h v font-lock-extra-managed-props RET`, and let me know what it says.

In a buffer with password hiding working:

```
font-lock-extra-managed-props’s value is nil
```

After breaking password hiding, as described above

```
font-lock-extra-managed-props’s value is (display) 
```

**Comment by DarthFennec** [comment]
Got it. The issue was that I never turned `font-lock-extra-managed-props` into a buffer-local variable, I guess I assumed it was like that by default. Since nothing in your setup sets it to be buffer local, it just defaults to global, which changes the value in every buffer.

I pushed a fix, give it a try and let me know.

**Comment by thblt** [comment]
It works perfectly, thank you!

**Comment by DarthFennec** [comment]
Excellent. I'll close this for now, then.
