### ISSUE TITLE
color-name-to-rgb not always available

### ISSUE THREAD

**Issue by sah** [DarthFennec/highlight-indent-guides#26]
On init, I get an error: "Autoloading failed to define function color-name-to-rgb"

Currently I'm working around it with `(setq highlight-indent-guides-auto-enabled nil)`.

    $ emacs -version
    GNU Emacs 25.2.1

**Comment by DarthFennec** [comment]
You say "not always available", does that mean this only happens sometimes and it loads fine other times?

It sounds like it's autoloading the function properly, but when it searches for the actual definition, it can't find it. This may be because you have another package shadowing it (`color-name-to-rgb` is defined in a file called `color.el`, so if you have another unrelated `color.el` that it looks in first, it won't find the function). You can use <kbd>M-x list-load-path-shadows</kbd> to check.

Hope that helps.

**Comment by sah** [comment]
Your guess about shadowing of `color.el` was right, and I've now found and fixed my issue. Thanks, and sorry to bother you!
