### ISSUE TITLE
How to erase this error message?

### ISSUE THREAD

**Issue by seagle0128** [DarthFennec/highlight-indent-guides#32]
When I start Emacs or install packages in terminal, I got this error message.
How to remove it? It's annoying. Thanks.

```
highlight-indent-guides cannot auto set faces: `default' face is not set properly
```

**Comment by DarthFennec** [comment]
That message means `highlight-indent-guides-mode` can't dynamically set the colors. Considering you aren't complaining that the guides aren't showing up, or are the wrong colors, I expect that you must be setting them manually? In that case, you should disable the dynamic coloring feature, as specified in the [readme](https://github.com/DarthFennec/highlight-indent-guides#highlight-colors):

``` emacs-lisp
(setq highlight-indent-guides-auto-enabled nil)
```

Let me know if that helps. Thanks.

**Comment by DarthFennec** [comment]
You're probably right. On a hunch, what is your `TERM` environment variable set to? Mine is `xterm-256color` and the feature works fine for me, but when I change it to something else I get the error you're getting.

**Comment by seagle0128** [comment]
```
 ~  echo $TERM
xterm-256color
```

**Comment by DarthFennec** [comment]
When you ran `echo $TERM`, were you in the same environment (inside tmux/ssh)? Your local machine, tmux, and the remote machine all use separate variables, and emacs will use the one it's directly running in (so if you're running emacs inside ssh inside tmux, it'll use the remote machine's `TERM`).

You could also try running tmux with the `-2` option, which forces 256 color support. I'm not sure if this will help, but it might be worth a try.

**Comment by seagle0128** [comment]
I don't think `$TERM` is the root cause. Even `$TERM` is `xterm-256`, the error message still exists.

I recreated the issue following below.

1. `export $TERM=xterm-256`
1. `mv ~/.emacs.d ~/.emacs.d.bak`
1. `git clone https://github.com/seagle0128/.emacs.d.git ~/.emacs.d`
1. `emacsclient -a "" -nw`

I doubt it may be related to `destop-mode` or something else, but not very sure so far.

**Comment by DarthFennec** [comment]
I see. It looks like this happens when I run emacs as a daemon. The daemon gives me the error message, and the colors are wrong in the client, but then if I reload the theme everything works fine afterward. Also, if I run it standalone, I don't get the error. Let me know if this is the behavior you're seeing. I'll see if I can find some way to handle this a little better.

**Comment by DarthFennec** [comment]
The latest commit fixes the issue for me. Please let me know whether it helps you. Thanks.

**Comment by seagle0128** [comment]
Thanks for the fixing, @DarthFennec.
I tested today. The most of errors disappear except one case. If `desktop-mode` is enabled, the error still exist while starting Emacs with daemon mode or server mode in terminal.

```elisp
Wrote /Users/vincent/.emacs.d/.emacs-devel.desktop.lock
Error: highlight-indent-guides cannot auto set faces: `default' face is not set properly
Desktop: 2 buffers restored.
```

**Comment by seagle0128** [comment]
Mmm... Wired, maybe. Did you enable `desktop-mode`?

**Comment by DarthFennec** [comment]
Yes. I added `(desktop-save-mode 1)` to my init, and I ensured that it saved a desktop file and started restoring my sessions. Then I ran:

```
emacsclient -a "" -nw
save-buffers-kill-emacs
emacsclient -a "" -nw
```

And I got:

```
Wrote /home/travisf/.emacs.d/.emacs.desktop.lock
Desktop: 1 frame, 1 buffer restored.
```

No error.

**Comment by DarthFennec** [comment]
I narrowed it down I think. In your `init-restore.el` file, you have the following:

``` emacs-lisp
  ;; Load custom theme
  (add-hook 'desktop-after-read-hook
            (lambda ()
              (dolist (theme custom-enabled-themes)
                (load-theme theme t))))
```

When I comment this out, the error goes away. I think this is because `desktop-after-read-hook` runs before the client starts. Since `highlight-indent-guides` calculates the colors whenever the theme changes (allowing the colors to change with the theme if you change it live), that ends up happening here.

Out of curiosity, what does this snippet actually do? The theme is already loaded by `init-ui.el`, but I assume there's some reason it needs to be loaded again here?

**Comment by DarthFennec** [comment]
Cool, glad I could help.
