### ISSUE TITLE
highlight-indent-guides.el not found in MELPA

### ISSUE THREAD

**Issue by aumars** [DarthFennec/highlight-indent-guides#37]
Installing highlight-indent-guides.el through `package-install` returns 

    highlight-indent-guides.el not found in MELPA

**Comment by DarthFennec** [comment]
What command are you running? <kbd>M-x package-install RET highlight-indent-guides RET</kbd> works for me.

**Comment by jgkamat** [comment]
If you haven't already, you might want to `M-x package-refresh-contents` as well. M-x package-list-packages should do this automatically.

**Comment by kirk86** [comment]
This needs to be re-opened since the package is not found melpa.stable.org

Please upload a stable version on stable.melpa.org. This is quite important for people who want stability over bleeding edge.

Here's the proof
![image](https://user-images.githubusercontent.com/2902390/66128960-d62ca680-e5e6-11e9-9e39-35f1e6442e9c.png)

![image](https://user-images.githubusercontent.com/2902390/66128983-e5135900-e5e6-11e9-85db-8e7053b02bd3.png)

**Comment by DarthFennec** [comment]
@kirk86 I'll seriously consider this. So far I haven't been inclined to release this on MELPA stable, since as far as I've been aware, most people don't need it. Also, my more guerrilla development style on this project (like the fact that there's no automated testing of any kind) causes me to hesitate in calling any version of it "stable" at all. I recognize that this is a shortcoming, and it's one I've been meaning to rectify, but I simply haven't had the time. Perhaps soon.

**Comment by kirk86** [comment]
> most people don't need it

Why are there better alternatives?

**Comment by DarthFennec** [comment]
Sorry if I wasn't clear, I meant that most people I'm aware of just use MELPA unstable and have no need for a stable release of this mode. You're the first person to ever approach me about releasing on MELPA stable.

**Comment by kirk86** [comment]
No worries,



> You're the first person to ever approach me about releasing on MELPA stable

That's because I got burned by author of third party packages changing the behaviour of their packages which on package updates will mess up with my config.

**Comment by jgkamat** [comment]
kirk86 writes:

> That's because I got burned by author of third party packages changing the 
> behaviour of their packages which on package updates will mess up with my 
> config.

This is a bit off-topic, but stable does not fix this issue. If someone 
releases a new stable version (2.0 from 1.0) which breaks behavior and 
previous config, it will still break your setup as melpa stable will still be 
updated.

A poorly maintained stable release is worse than none at all, as it can lead 
to the unstable version being less buggy than the published one.

**Comment by DarthFennec** [comment]
Sure, I've been burned by that too. There's nothing worse than deciding to run an update right before an important demo and then suddenly not being able to use your editor. But I agree with @jgkamat about this, you're still going to have that problem with stable. What I do is, I put off running updates until I know I have some free time to recognize and fix config discrepancies, instead of when I actually need emacs to work.

One of the main reasons I'm on the fence about this is my own experience with stable vs unstable projects. When I use a program, I usually install the stable version, and then later switch to the unstable version, once I find out it has features and bugfixes I need that the stable version doesn't have. The unstable version is nearly always the better choice in my opinion, as long as it's not so unstable to be downright broken and unusable. And I don't think `highlight-indent-guides` has ever been in that state.
