### ISSUE TITLE
highlight-indent-guides slows down startup of swiper

### ISSUE THREAD

**Issue by CSRaghunandan** [DarthFennec/highlight-indent-guides#4]
@abo-abo 

There seems to be a minor issue with `highlight-indent-guides-mode` and `swiper`. Looks like enabling this will slow down the startup time of `swiper` to about 1-2 seconds on large files (over 1000 lines long). But, subsequent invokes of `swiper` without making any changes to the files will be normal. 

I tested this in `emacs -Q` as well and there was a second lag when invoking `swiper` with `highlight-indent-guides-mode` enabled(tested on a large file). Can someone confirm if this is the case?

I guess the lag is here because this uses `font-lock` to draw indent guides?

**Comment by DarthFennec** [comment]
Yay, an excuse to install Ivy! I've been meaning to, but I haven't gotten around to it >.>

After looking around a little, I think this may be caused by something called `swiper-font-lock-ensure`. Basically, `swiper` narrows the buffer in the search results as you type, and preserves syntax highlighting in those results. In order to do this in a timely manner, it uses `font-lock-ensure` to precalculate the `font-lock` for the entire buffer when it starts. What `highlight-indent-guides` does is relatively heavy, and it can only get away with doing it quickly because `font-lock` is lazy and only calculates for the visible parts of the buffer. But when `swiper` forces it to calculate the entire buffer all at once, it ends up taking a while. That's my theory anyway.

Assuming this is indeed the case, I can think of two potential fixes. My preference would be to disable `highlight-indent-guides` temporarily while `swiper-font-lock-ensure` is running. It's not like the indentation is that important to see in the search results anyway. But I'm not sure what the best way to go about this would be. A simpler solution would be to just disable `swiper-font-lock-ensure` when `highlight-indent-guides` is loaded (`swiper` already has a list of 'incompatible' major modes that it does this for). But I expect this might cause some performance issues during the actual interactive search.

I'll look more into this and see if I can discover anything else.

**Comment by DarthFennec** [comment]
I've been using `swiper` for a few days now, trying to do random searches on large files as soon as I open them, with `highlight-indent-guides` running. I've done this with up to 3000-5000 line files, in `c-mode` and `emacs-lisp-mode` mostly, and most of the startup lag I've encountered has been well under half a second (the worst of it is still under a second). It's possible that `highlight-indent-guides` is  simply exacerbating an otherwise insignificant lag caused by some other mode you have loaded. It's also possible that I'm just using faster hardware than you, or that the files you're searching have a lot more indentation than the files I'm using. I don't really know.

**Comment by CSRaghunandan** [comment]
I did a huge cleanup of my emacs config  in the past few days and apparently, I had a stale projectile cache (which somehow was 115mb big!  I have no idea how it got so big) which was causing slowdowns in emacs. I tested `highlight-indent-guides-mode` and it seems better than before. It's definitely not taking as long as before. which is great :) Though there is a very tiny lag when on very large files, but that's acceptable I suppose.

**Comment by DarthFennec** [comment]
There will always be some lag on very large files, I don't think there's much we can do about that. As long as it's an acceptable amount, I don't think it's worth adding special handling. I've been wanting to try and optimize some of the drawing methods, so once I get around to that it should also help a bit. For now though, I think we're done with this one.
