### ISSUE TITLE
Implementation of continuous lines

### ISSUE THREAD

**Issue by rememberYou** [DarthFennec/highlight-indent-guides#42]
First of all, a big thank you for the package. 

A concern that I have encountered and that I could not find a solution, is the fact that the lines are not continuous since it cuts when inserting empty lines.

SEE: https://ibb.co/jXu8QJ

I think it's annoying behavior. In any case, it might be interesting to create a boolean variable to know if it is a user's choice to keep these lines cut or not.

Also, this behavior is also problematic when inserting empty lines. I noticed that the line is drawn only after a character is inserted, but I prefer that even if I insert an empty line, the line be drawn.

SEE: https://ibb.co/nBgSKd

To conclude, in my opinion, lines should not be cut (except if the user must want it), and these lines should be drawn to the last line of the buffer and also when inserting empty lines, not when I write a character.

What do you think?

**Comment by DarthFennec** [comment]
I like this idea, it's a good one. However, as stated in the [readme](https://github.com/DarthFennec/highlight-indent-guides#limitations), and as described in detail in issues #19, #21, and #31, it appears to be impossible to do with the current design of the mode.

Instead of using overlays (which can get slow if there are too many in the buffer at once), this mode draws indent guides directly onto whitespace characters. This is fast, works well, and doesn't interfere with other modes as much. However, empty lines have no whitespace characters to draw guides on, so guides simply can't be drawn on those lines.

There are only a few possible ways around this, as far as I can tell:

- Redesign the entire mode to use overlays, and just deal with any potential performance penalty or interference with other modes.
- Only use overlays where it would be impossible not to, which would reduce the performance impact, but not the interference issue. This would also overcomplicate the codebase to a degree I'm uncomfortable with.
- Find a way to do it without using overlays. The only approach I've found so far is to highlight linefeed characters, which sort of works, but has its own set of quirks. Also it appears to interfere with any mode that uses end-of-line overlays, including but not limited to `fill-column-indicator`, which as far as I know is used by most people. So this isn't really an option at the moment.

It's possible that a decent solution will present itself eventually. Maybe I'll find an acceptable way to do the linefeed highlighting. Maybe I'll find an optimal approach for switching to overlays. Or maybe something else will come along. In the meantime, I don't think this is going to happen.

**Comment by rememberYou** [comment]
Thank you for your answer. Similarly, I do not have the immediate solution, but I would be happy to contribute if I can find one.

Also, sorry for this duplicated issue.
