### ISSUE TITLE
Howto: highlight children blocks instead of the parent block

### ISSUE THREAD

**Issue by vemv** [DarthFennec/highlight-indent-guides#44]
Hi again!

In the example screenshot, being the cursor positioned at `final-fragments`, I'd expect the highlighted line to be the one below `final-fragments`, not the one below `let*`.

![image](https://user-images.githubusercontent.com/1162994/43697603-9d8dd68a-9945-11e8-8aee-fb2d06ded80b.png)

Not sure if `Custom Highlighter Function` can do that?

Would appreciate a recipe. Given this is the default behavior in e.g. Atom I think other people may want it too.

Thanks - Victor

**Comment by DarthFennec** [comment]
I hadn't thought about this. `final-fragments` is in the `let*` block, so I'd expect that to be the highlighted block. I don't use Atom so I'm not certain of the behavior, but I expect this is a special case specifically for lines immediately followed by a new block?

This isn't currently possible with the custom highlighter function, since by the time that's called, the mode has already decided which block is the current one. I think it would be possible to do this by advising the `update-line-cache` function. Not sure about exact code at the moment, but it shouldn't be hard.

**Comment by vemv** [comment]
I was incorrect about my claim on Atom (`indent-guide-improved` package, specifically) - the highlighting behavior is equivalent. Hadn't used Atom in a few months!

Still, I think I'd find the described feature really useful/intuitive. Ideally, one could switch between the two criteria just with a keystroke, as there are some cases where one is better than the other (really depends on what activity the developer is doing, how is the code shaped, how big is the viewport, etc)

**Comment by vemv** [comment]
Hi!

Thanks for the snippet, much appreciated.

It appears to work fine!

Would be nice to add it to the package so it's 'official', and doesn't potentially break with new releases.

Cheers - Victor

**Comment by DarthFennec** [comment]
I'm not sure I like the idea of adding this to the package. As you say, this isn't actually how Atom works, and I doubt this is how other editors work as well. You're the only person I've heard of who prefers it this way. And I really don't want to get into the habit of adding features that only one person is going to use, especially if there's a workaround that does the trick just as well.

I doubt the snippet is going to break, at least not any time soon, but if it does you can open a new issue. Thanks!

**Comment by vemv** [comment]
Alright then!
