### ISSUE TITLE
Howto: customize face for current line

### ISSUE THREAD

**Issue by vemv** [DarthFennec/highlight-indent-guides#45]
Under my config:

```
(setq highlight-indent-guides-character ?·
      highlight-indent-guides-method 'character
      highlight-indent-guides-responsive 'top
      highlight-indent-guides-auto-enabled nil)
(set-face-foreground 'highlight-indent-guides-character-face vemv-default-foreground-color-much-darker)
(set-face-background 'highlight-indent-guides-top-character-face vemv-colors/purple)
(set-face-foreground 'highlight-indent-guides-top-character-face vemv-colors/purple)
```

...indentation guides are either purple blocks, or grey dots:

![image](https://user-images.githubusercontent.com/1162994/44014038-c69fd896-9ec9-11e8-97b9-075ea245dd0f.png)

However, if I place the cursor in certain lines, I will get a mixed character:

![image](https://user-images.githubusercontent.com/1162994/44014229-f68cfb46-9eca-11e8-9b37-ddb871f2163e.png)

It's a bit hard to see, but it's a purple dot.

I'm not sure if that's intentional behavior. Would it be possible to turn the purple dot into a purple block?

(for the sake of reproducibility, for this bug report I'm not applying this unrelated patch https://github.com/DarthFennec/highlight-indent-guides/issues/44#issuecomment-411486188 )

**Comment by DarthFennec** [comment]
It looks like you have `hl-line-mode` or something enabled, which sets the background color of the current line. This background color is overriding the purple background around your dot, causing the dot to show up.

I'm not certain what can be done about this. The colors can be changed using the custom highlighter function, but the displayed character cannot. Since the purple background isn't an overlay, it can't be given priority over competing faces, because emacs says so. It might be possible to customize your `hl-line-mode` (or whatever it is) to not draw on that tile, but I'm not sure.

**Comment by vemv** [comment]
Good catch! Fantastic, thank you.

So I disabled hl-line-mode just for the specific major modes using highlight-indent-guides (https://stackoverflow.com/a/9992499) and it looks correct now.
