### ISSUE TITLE
How to properly disable highlight-indent-guides in Lisp?

### ISSUE THREAD

**Issue by re-mx** [DarthFennec/highlight-indent-guides#48]
Hello,

 I don't want to enable `highlight-indent-guides` in Lisp and its related languages, so I wrote the following function:
```elisp
(defun remx/disable-highlight-indent-guides ()
  (when (bound-and-true-p highlight-indent-guides-mode)
    (highlight-indent-guides-mode -1)))
```
And add it to the major-mode hook of the Lisp related language.

However, I found that I was experiencing startup performance issues, which may be caused by the fact that I did not change the major-mode of the scratch-buffer.

Is there any way to alleviate this problem? thank you very much.

and sorry for my poor English.

**Comment by jgkamat** [comment]
Hi,

How are you enabling highlight-indent-guides? It does not enable itself
automatically.

If you are using this snippet from the readme:

(add-hook 'prog-mode-hook 'highlight-indent-guides-mode)

Why not instead change it to something like:

(add-hook 'prog-mode-hook
	(lambda ()
		(unless (eq major-mode 'lisp-mode)
			(highlight-indent-guides-mode))))

I think that will be more easy to debug than enabling it everywhere then
selectively disabling it, as I don't know what order the hooks get run in.

MX Reimu writes:

**Comment by DarthFennec** [comment]
I don't see `indent-guide-mode` being enabled anywhere in that configuration. Do you know what it does to enable the mode, and did you change that code too?

The major mode of the scratch buffer is `lisp-interaction-mode`, so if you need to disable it in that buffer you can use that. I doubt this will help you with startup performance, though.

First of all, I sort of doubt your startup performance issues are actually caused by this, since `highlight-indent-guides` is pretty good about being quick to work. Also, the scratch buffer is generally not very large at all (only a few lines on startup), which is not going to take very long at all to draw.

Secondly, if your startup is in fact slow because `highlight-indent-guides` is being enabled in your scratch buffer, your approach (enabling and then disabling the mode) won't make things go any faster. If anything it'll be slower, since instead of just enabling the mode, it has to enable it and then disable it.

It's a much better idea to only enable it in the modes you want to use it in, as @jgkamat described.

**Comment by re-mx** [comment]
There is indeed a process of "enable first and then disable".

Enable code:
```emacs-lisp
(when (package-installed-p 'highlight-indent-guides)
  (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)
  (setq highlight-indent-guides-method 'character)
  (setq highlight-indent-guides-responsive 'top))
```
Perhaps because you use `font-lock` to implement `highlight-indent-guide`, this process makes the startup time unstable. Sometimes it is very fast, sometimes it is very slow.

Maybe the @jgkamat 's method is a good way, I will try.

Another reason I don't do this is because I don't know which of the major-modes that purcell has enabled to turn off the 'indent-guide` function.

**Comment by re-mx** [comment]
Thanks.
