### ISSUE TITLE
[Feature request] Option to have guides display fixed intervals

### ISSUE THREAD

**Issue by ideasman42** [DarthFennec/highlight-indent-guides#5]
Currently indentation guides follow the text (which may be nice for some users),
however it can be useful to have the indent guides simply follow the indent size.

This way if you have a file using 4 spaces indentation and a block which is accidentally indented 7 spaces instead of 8 (for example) - it will be more obvious.

----

Note, its possible this might be better implemented as a different plugin.

**Comment by DarthFennec** [comment]
I've considered having this as an option, and I've generally decided against it. As far as I can tell, the vast majority of users don't insert indentation manually, and prefer to use tools like the tab key, `electric-indent-mode`, `indent-region`, [`aggressive-indent-mode`](https://github.com/Malabarba/aggressive-indent-mode), etc, so practically speaking there aren't really any situations where an indent would be, say, seven spaces instead of eight. Also, even in languages that generally follow strict indent widths, there are situations where major modes will do alignment-based indentation (say, if you hard-wrap an argument list, the next line will generally align to the opening parenthesis character), and static indentation guides don't look very good when this happens. Even disregarding this, the results of static and dynamic guides would be exactly the same for these kinds of languages, so there really isn't a reason to use static guides over the alternative.

In my mind, the purpose of indent guides is to make it easier for your eye to follow the indentation that exists in the buffer, not to help enforce an indentation style. Imagine that you're editing someone's code, to make a pull request or something, and they used the wrong numbers of spaces for some nested blocks. To keep your PR simple and focused, you leave the indentation the way it is (it's not as if the compiler cares anyway, and the code is still readable). Would you really prefer to edit this code when all the indent guides in these blocks are offset and wrong? I would think this would make it much less readable.

If you're looking for something to help you keep your indentation consistent, I would suggest using the tab key (which re-indents the current line to the correct position), possibly in conjunction with `electric-indent-mode` (which correctly indents new lines automatically when you press enter). To force correct indentation on a block, use `indent-region` on that block. Alternatively, you can use [`aggressive-indent-mode`](https://github.com/Malabarba/aggressive-indent-mode) to force indentation to continuously stay correct as you edit (this isn't for everyone, but a lot of people swear by it, so I thought I'd mention it). If you just want to be told if/where a buffer has incorrect indentation, you can just do a search for it, something like `^ \{4\}* \{1,3\}[^ ]`, or write a function to do it that could be a little smarter about it. If you really want a mode that will draw guides using a pre-configured indent width, you can try out [`highlight-indentation-mode`](https://github.com/antonj/Highlight-Indentation-for-Emacs), which is pretty mature and popular, and draws its guides statically rather than dynamically.

**Comment by ideasman42** [comment]
Thanks for the comprehensive reply.
As stated, I've since discovered that most emacs users prefer automatic indentation.

Nevertheless, there are cases where large code-bases don't have 100% consistent indentation across all modules, where you may want to edit someone elses code without re-indenting large blocks causing noisy diffs.
Where not all users have the same editor.
Indentation regarding argument wrapping for example may depend on the developers preference too.

Anyway, I'll try `highlight-indentation-mode`.
