### ISSUE TITLE
highlight-indent-guides makes plot not working

### ISSUE THREAD

**Issue by seagle0128** [DarthFennec/highlight-indent-guides#55]
I am using `ein` to develop. If `highlight-indent-guides` is enabled, the images (`plot`) aren't displayed. No errors and warnings are observed.

env:
- GNU Emacs 26.1
- macOS Mojave
- [Centuar Emacs confg](https://github.com/seagle0128/.emacs.d)

**Comment by DarthFennec** [comment]
Looks like `ein` draws images by writing a character to the buffer, and then changing its `display` property so that the character displays as the appropriate image. However, `highlight-indent-guides` sets the `display` property to be managed by `font-lock`, otherwise highlighting wouldn't work properly. Once `font-lock` is managing `display`, all uses of `display` outside of `highlight-indent-guides` no longer work, which explains why your images aren't showing up. I think the best workaround for the moment is to simply disable `highlight-indent-guides` in your `ein` mode.

It appears that the `display` property is the standard method of displaying images in emacs. I didn't realize this before, and it's somewhat worrying to me because it means `highlight-indent-guides` cannot be used in any mode that supports images. There doesn't appear to be any sort of workaround for this. The most officially correct (and likely the only) solution is to redesign the mode to use overlays. I'm seriously considering giving this a try, because it would fix nearly every shortcoming I've come across, including highlight priority issues, `whitespace-mode` incompatibilities, and the inability to draw guides across empty lines. On the other hand, this redesign would be quite the timesink, and using large numbers of overlays like this would require is known to be extremely suboptimal, and I'd rather not put all this effort into such a change only to later realize that it makes things unusably slow.

I'll think on it more. In the meantime, I don't think there's much I can do about `ein`.

**Comment by seagle0128** [comment]
Thanks for the reply! That's what I am doing. This is a workaround, but I am fine to close it.

**Comment by DarthFennec** [comment]
An ignore/exclude list, as in, a list of modes that `highlight-indent-guides` shouldn't be used for? It doesn't work that way right now, as it's a buffer-local mode, so by default it doesn't load into any buffer unless you explicitly tell it to. I could certainly add a global mode option with customizable include/exclude lists. That will probably be a good minor usability feature.

**Comment by seagle0128** [comment]
Right! Waiting for the replacementation of this amazing package. Thanks!
