### ISSUE TITLE
Slow when handling the buffer

### ISSUE THREAD

**Issue by seagle0128** [DarthFennec/highlight-indent-guides#56]
Hi, Thanks for the amazing package! I love it.

I am experiencing the slaggy issue while handling this small file (or similar buffers): https://github.com/seagle0128/icons-in-terminal.el/raw/master/icons-in-terminal-data.el. 
I did the profiling, and confirmed it was caused by `highlight-indent-guides-mode`. After turning off it, the issue disappears.

Pleas take a look, thanks!

**Comment by DarthFennec** [comment]
You're working with very large indent blocks, which I expect is why you're seeing issues. Even so, basic motion and editing shouldn't be unreasonably slow (with the file you linked I'm getting a barely noticeable amount of lag, if any at all).

`highlight-indent-guides` primarily focuses on the current indentation block when doing calculations. Since you're much more likely to be working on smaller, deeper blocks rather than larger, shallower ones, the mode tends to work well regardless of the overall size of the file, since what really matters is the sizes of the individual blocks. However, this design starts to break down if you have large flat blocks like these data structures. In this case, some actions should cause little to no slowdown, while others might create a lot.

Actions that shouldn't cause much (or any) lag:

- Motion. Moving around in the buffer should be pretty fast, and cause little to no noticeable lag.
- Simple line modifications. Changing non-indentation text on a line, or adding or deleting a line within an indent block, should not cause any lag.
- Basic indentation. Adding more indentation to a deeply-indented line should not cause any lag.

Actions that can cause large amounts of lag:

- Major indentation changes. Deleting indentation from a line, when there are a large number of consecutive lines below it that have more indentation, will cause large slowdowns. This is because the guide columns for those lines are moving around and changing shape, which means each line that displays said guide columns must be updated. The more lines there are in the block, the more updates need to be made, and this introduces slowness.

This can be visualized like so (disregard that this is poor formatting for an `if`):

```
 1 (if x                 1 (if x
 2 |      (do-y)    -->  2 |  (do-y)
 3 |      | (do-z)       3 |  |     (do-z)
 4 |      | ; ...        4 |  |     ; ...
```

As line 2's indentation changes, the guide columns on lines 3 and 4 also change. If those guide columns descend for hundreds or thousands of lines before the block ends, any change to line 2's indentation will trigger updates on all of those lines, which can freeze emacs for several seconds.

Since your innermost blocks are upwards of 500-1000 lines long, I wouldn't be surprised if you got some slowdown on some kinds of editing actions. However, I want to make sure you're not getting weird lag in places where you shouldn't. Does the lag you're getting seem to match what I'm describing? If not, what sort of actions seem to trigger it?

**Comment by seagle0128** [comment]
Thanks for the quick reply and very detailed information!

Your description is pretty correct. The slowdown is not acceptable. The cursor can be moved anyway, but feel slaggy, especially while changing the indentation with `aggressive-indentation-mode`. The situation is better after disabling one of both, but it's obviously better if disabling `highlight-indent-guides-mode`.

**Comment by DarthFennec** [comment]
Hm ... even with `aggressive-indent` also enabled, I don't see any real slowdown during motion or editing. At worst, I get some lag when paging thorough the document as quickly as possible, but outside of that, all types of motion and common types of edits feel normal to me.

Are there specific types of edits you're doing a lot of that are particularly slow? Changing indentation of course is going to be, but with `aggressive-indent` turned on that should be relatively static. I can't think of much else that would cause something like this. Perhaps there's some other mode interfering? Or perhaps my hardware just handles the load better.

Unless there's something obvious that we're missing, I don't think I can do anything about this. The mode is optimized specifically for the most common case: small heavily-edited blocks inside of large lightly-edited blocks. I suppose what I can try to do is leverage [emacs threads](https://www.gnu.org/software/emacs/manual/html_node/elisp/Threads.html) (i.e. coroutines) to pause the redraw every N lines to allow for interleaved interaction. That wouldn't make the redraw go any faster, but it would allow emacs to continue to function while the redraw is happening. I would need to carefully design this so that further edits to the same block while the redraw is in progress are handled properly, but it's a possibility.

I didn't notice much difference when I tried this myself, but if you don't have `electric-pair-mode` turned on, you might want to try that. Inserting unclosed parentheses or quotes might trigger a redraw of the rest of the block, which could waste a lot of cycles. `electric-pair-mode` auto-closes those things for you before `highlight-indent-guides` can trigger, so unnecessary redraws might be avoided.

**Comment by seagle0128** [comment]
`electric-pair-mode` is enabled in my env. I am using MacBook Pro 13' 2015. Maybe the hardware is poor :(  That's what I only think of. I have no idea and clue so far.

**Comment by DarthFennec** [comment]
I'm on a MBP 15" 2015, which I expect is probably a little better than the 13", but it shouldn't be by much ... how strange. If I find anything else that might be the cause, I'll let you know. Otherwise I guess just disable the mode in those buffers. I can start looking into the threads option, but I don't think I'll have time to work on it much in the forseeable future. But thanks for opening the issue!
