### ISSUE TITLE
Error running timer ‘highlight-indent-guides--try-update-line-cache’ when using responsive guides

### ISSUE THREAD

**Issue by vishesh** [DarthFennec/highlight-indent-guides#59]
I'm running on configuration (on Emacs 26.2 build 1, Fedora 30, `highlight-indent-guides-20190108.3`):

```elisp
(setq highlight-indent-guides-method 'character)
(setq highlight-indent-guides-responsive 'top)
```

When using the responsive guide feature I get following error:

```
Error running timer ‘highlight-indent-guides--try-update-line-cache’: (void-function put-text-property-unless-ignore)

Debugger entered--Lisp error: (void-function put-text-property-unless-ignore)
  put-text-property-unless-ignore(132 133 face highlight-indent-guides-top-character-face)
  highlight-indent-guides--overdraw(#<marker at 132 in size.cpp> #<marker at 277 in size.cpp>)
  highlight-indent-guides--try-update-line-cache()
  apply(highlight-indent-guides--try-update-line-cache nil)
  timer-event-handler([t 0 0 100000 t highlight-indent-guides--try-update-line-cache nil idle 0])
```

**Comment by vishesh** [comment]
Closing. Seems like some other package was misbehaving. Cleared my entire `elpa` directory (kept `customs.el` although).

**Comment by DarthFennec** [comment]
Oh, cool, glad you got it working.

It looks like `font-lock-plus` defines `put-text-property-unless-ignore`, and also reimplements standard font lock functions so that they call `put-text-property-unless-ignore`. The fact that the function doesn't appear to exist, but the override is still happening, seems very strange to me. It definitely seems like a misbehavior in that package, though.
