### ISSUE TITLE
Don't indent the first level

### ISSUE THREAD

**Issue by radik909** [DarthFennec/highlight-indent-guides#6]
Reference: https://github.com/zk-phi/indent-guide/issues/30

Is there a way/command to avoid indenting the first level?

**Comment by DarthFennec** [comment]
I sort of agree with zk-phi, this seems pointless to me. But yeah sure, it wouldn't be too hard to add something like that. I'll give it a shot as soon as I have some time.

**Comment by Yevgnen** [comment]
Any news ?

**Comment by wbolster** [comment]
i would like to see a minimum level, e.g. when editing python source code anything below 8 spaces of indentation is usually not interesting to me (e.g. class methods), and the visual overhead makes it harder to look at the code.

**Comment by DarthFennec** [comment]
@wbolster Sounds good to me.

I haven't had a chance to look at this yet, I don't know when I will. Hopefully soon.

**Comment by DarthFennec** [comment]
Apologies for the ridiculous wait, real life got in the way >.>

I've gotten a few requests for various customization features similar to this one. Instead of having support for each specific feature, I decided to add general support for all of them. Another feature I've been working on is ["responsive guides"](https://github.com/DarthFennec/highlight-indent-guides#responsive-guides), which required a major refactor of most of the code. I found that this feature was much better suited to the refactored code, so I waited on this in order to implement both features at once.

You can now define a [custom "highlighter" function](https://github.com/DarthFennec/highlight-indent-guides#custom-highlighter-function), and implement your own logic to decide whether an indent guide is shown, and which face to use for it. This can be pretty powerful, but if you just want to hide the first guide line, you can do:

``` emacs-lisp
(defun my-highlighter (level responsive display)
  (if (> 1 level) ; replace `1' with the number of guides you want to hide
      nil
    (highlight-indent-guides--highlighter-default level responsive display)))

(setq highlight-indent-guides-highlighter-function 'my-highlighter)
```

Let me know if you have any issues.

**Comment by jgkamat** [comment]
Just wanted to say this is amazing, I just noticed the responsive guides too, which blows my mind. You should add some new gifs of reponsive guides in action.

I'd say this issue can be closed :)

**Comment by DarthFennec** [comment]
@jgkamat Whoops, I guess the gif was way too big, and it caused my LFS usage to skyrocket, to the point that Github has now disabled LFS for the rest of the month >.> Hosting the gif on Imgur now, but I had to get it under 10MB or else Github wouldn't allow me to link it. So I optimized it as best I could. The color assignments are a little off, but in all I think it looks alright. The file is now 2MB instead of 25MB, so it should load much faster now when visiting, which is a plus. I'd rather host it on Github instead of Imgur, but I don't want to put it directly in Git and I can't put it in LFS, so I'm wondering if there's a better way. I expect if I attach it in an issue, it'll become hosted and I can copy the URL from there. That seems like a weird workaround though.

Tangent aside, it looks like I got a hooray react from OP, which tells me he's aware of the update and hasn't had any problems with it worth further communication. So I'm just going to close this. Feel free to respond or reopen if necessary.

**Comment by dakra** [comment]
@DarthFennec how did you create the gif?
From looking at it, it should be very small.
I can recommend https://github.com/ambrevar/emacs-gif-screencast
makes very small Emacs gifs with good quality.

**Comment by DarthFennec** [comment]
@dakra I used ffmpeg to record a video and dump the frames, and imagemagick to convert it to a gif, and then I optimized it in gimp (I also tried optimizing with gifsicle, but it didn't help much). That screencast package looks pretty nice though, I'll take a look. Thanks!

**Comment by DarthFennec** [comment]
@dakra Yes, that was much better. New gif has perfect colors and is only 300KB. Thanks for the tip!
