### ISSUE TITLE
[Optimization] - Is a bit slow to use.

### ISSUE THREAD

**Issue by jcs090218** [DarthFennec/highlight-indent-guides#61]
First, thanks to this amazing package! I love it! :D

I have a file with 50 lines of codes. It started to lag when navigating with the cursor. Once I disabled `highlight-indent-guides` everything goes smoothly again.

**File Type:** `.ts`
**Major-mode:** `typescript-mode`
**Emacs Ver.** `26.3`
**OS:** `Windows 10`

If you curious about the file, here is the file.
```ts
/**
 * $File: Random.ts $
 * $Date: 2019-09-26 14:30:59 $
 * $Revision: $
 * $Creator: Jen-Chieh Shen $
 * $Notice: See LICENSE.txt for modification and distribution information
 *                   Copyright © 2019 by Shen, Jen-Chieh $
 */

namespace GBEgret {
    /**
     * @desc Random Util (亂數類)
     */
    export class Random {
        /**
         * @desc Generate random floating point number. (亂數取浮點數)
         * @param { number } min : Mininum floating point number. (最小浮點數)
         * @param { number } max : Maxinum floating point number. (最大浮點數)
         * @return { number } : Random generated floating point number. (亂數浮點數結果)
         */
        public static rangeFloat(min : number, max : number) : number {
            return Math.random() * (max - min) + min;
        }

        /**
         * @desc Generate random floating point number, include maxinum number.
         * (亂數取浮點數,包括最大數)
         * @param { number } min : Mininum floating point number. (最小浮點數)
         * @param { number } max : Maxinum floating point number. (最大浮點數)
         * @return { number } : Random generated floating point number. (亂數浮點數結果)
         */
        public static rangeFloatInclude(min : number, max : number) : number {
            return Math.random() * (max - min + 1) + min;
        }

        /**
         * @desc Generate random integer number. (亂數曲整數)
         * @param { number } min : Mininum integer number. (最小整數)
         * @param { number } max : Maxinum integer number. (最小整數)
         * @return { number } : Random generated integer number. (亂數整數結果)
         */
        public static rangeInt(min : number, max : number) : number {
            return Math.floor(Random.rangeFloat(min, max));
        }

        /**
         * @desc Generate random integer number, include maxinum numer.
         * (亂數曲整數,包括最大數)
         * @param { number } min : Mininum integer number. (最小整數)
         * @param { number } max : Maxinum integer number. (最小整數)
         * @return { number } : Random generated integer number. (亂數整數結果)
         */
        public static randIntInclude(min : number, max : number) : number {
            return Math.floor(Random.rangeFloatInclude(min, max));
        }
    }
}

```

**Comment by DarthFennec** [comment]
I don't have any trouble with that file, using the same major mode and emacs version. Perhaps it's some interaction with another minor mode, or some custom code? What else do you have loaded that we might be able to rule out? Thanks.

**Comment by jcs090218** [comment]
Hi! I disabled all the minor modes in that file and only have left this plugin turn on. But the problem remains unsolved. And I don't think `major-mode` matters because even with other major-mode the lag remained.

**Comment by jcs090218** [comment]
Okay, I have check the code and enabled `highlight-indent-guides-responsive` have solved my issue here! Thanks!

**Comment by jcs090218** [comment]
Never mind, is still slow even I turned on `highlight-indent-guides-responsive`. But it is better when I have it on! Do you think this would give you enough clue to know what the problem is?

**Comment by DarthFennec** [comment]
>Never mind, is still slow even I turned on `highlight-indent-guides-responsive`. But it is better when I have it on! Do you think this would give you enough clue to know what the problem is?

This doesn't make sense to me. `highlight-indent-guides-responsive` only adds rendering steps, so if anything it should be a little slower, or at least comparable. Definitely not faster.

>**Edit:** I realized having `highlight-indent-guides-method` set to `'column` is faster than setting it to `'character`. It make me feel like the performance is spending time on redrawing the character yet is fine with face? :/

It should be exactly the same. It's redrawing the cell either way, whether it's with a solid color or a character shouldn't matter as far as performance goes.

>**Edit 2:** I think there are also issue with Chinese characters. When I removed **MOST** Chinese characters; the plugin works well. :/

This is also very surprising, as emacs should be treating all characters equally. Also, `highlight-indent-guides` doesn't touch any of the text, only the indentation, so as far as the mode is concerned it doesn't matter what else happens to be on the line.

>And I think there is something wrong with the rendering too? Few lines in front of comments are missing.

That's intentional. Multiline strings and multiline comments don't get indent guides, because the whitespace isn't really indentation, it's just part of the string or comment. Also since major modes tend to set special faces for comments and strings, the highlighting would be inconsistent if guides showed up there anyway.

I really don't know what you're experiencing here, though. None of this makes any sense to me, and I can't reproduce any of it. Maybe it's something to do with the Windows distribution of emacs? I'm testing this with emacs on Linux and Macos with no issues, and my configurations are otherwise identical to yours, as far as I can tell.

**Comment by jcs090218** [comment]
I agree, I am only working on Windows and Linux usually works well... And what I am experiencing is the plugin is very unstable. I couldn't figure out what and when this plugin starting to lag...

**Comment by jcs090218** [comment]
Note: Even I tested on Linux is still slow. :/

**Comment by jcs090218** [comment]
Okay, I think the issue is my highlighting implementation. That is why it cost so many performance on `post-command-hook`. Close this for now.

**Comment by DarthFennec** [comment]
Glad you seem to have figured it out. I'll answer your earlier questions, in case you're curious:

>Do you think the `jit-lock-register` is necessary?

Absolutely, this is what makes the mode work. `highlight-indent-guides--guide-region` re-assigns guide positions in a region, based on the actual indentation, so it needs to re-run whenever the text changes so that the guides stay accurate. `jit-lock-register` is designed to do this in a reasonably optimal manner; it's a built-in emacs function that binds `highlight-indent-guides--guide-region` into the `font-lock` cycle, meaning it will run whenever a region changes enough to require any refontification. By nature, this will often happen when it doesn't need to, but `highlight-indent-guides--guide-region` is optimized for that situation, so it should complete very quickly unless there are real indentation changes.

>this actually solved my issue because `highlight-indent-guides--guide-region` got executed multiple times using `jit-lock-register`.

Makes sense, considering it reduces the number of times the function runs. Of course, this isn't a good solution, since doing a string compare on the entire buffer all the time isn't optimal for larger buffers. The current optimizations are generally enough.

**Comment by jcs090218** [comment]
Thanks for your answer! I greatly appreciated it! :D

**Comment by Gleek** [comment]
For any one stumbling on this. The performance, for me, greatly improved after settings `auto-window-vscroll` to `nil`
