### ISSUE TITLE
reference to free variable ‘highlight-indent-guides-mode’

### ISSUE THREAD

**Issue by kirk86** [DarthFennec/highlight-indent-guides#62]
Hi and thanks for the package.
I was wondering if you have any insights on why I keep receiving this warning:
`Warning (bytecomp): reference to free variable ‘highlight-indent-guides-mode’`

My installation is as follows:
```
(use-package highlight-indent-guides                                            
   :ensure t                                                                     
   :config                                                                       
    (add-hook 'prog-mode-hook 'highlight-indent-guides-mode)                     
    (setq highlight-indent-guides-method 'column))
```
Am I doing sth wrong?

**Comment by DarthFennec** [comment]
Weird. I don't think you're doing anything wrong, it looks fine to me. Is this warning just cluttering the logs, or is the mode actually being prevented from loading?

**Comment by kirk86** [comment]
@DarthFennec Thanks for the reply. Those warning happen the first time that I fire up emacs when use-package installs and byte compiles the packges.

**Comment by DarthFennec** [comment]
The fact that it loads and runs fine shows that the mode is clearly available (as opposed to missing, which is what the error message implies). There's no reason I know of that it should be missing at this stage, and I've seen other people's configs and they look no different from yours. I really couldn't tell you why this is happening. Since it just appears to be cluttering the logs, I'd simply ignore it for now. If I come across any more insight about this, I'll let you know. Thanks!
