### ISSUE TITLE
use different colors for character in odd and even column

### ISSUE THREAD

**Issue by WeissP** [DarthFennec/highlight-indent-guides#64]
Is there a way, to use different colors for character in odd and even column?
or make only first indent column invisible?

**Comment by DarthFennec** [comment]
The feature you're looking for is the [custom highlighter function](https://github.com/DarthFennec/highlight-indent-guides#custom-highlighter-function). This allows you to write your own function to decide how the highlights work. Here are a couple of examples:

### Make only the first indent column invisible

Just like the example in the README:

```emacs-lisp
(defun my-highlighter (level responsive display)
  (if (> 1 level)
      nil
    (highlight-indent-guides--highlighter-default level responsive display)))

(setq highlight-indent-guides-highlighter-function 'my-highlighter)
```

### Use different colors for character in odd and even column

Because there's only one character face defined by the mode, you'd need to define the second one yourself. Something like:

```emacs-lisp
(defface my-highlighter-even-face '((t :foreground "red")) "")
(defface my-highlighter-odd-face '((t :foreground "blue")) "")

(defun my-highlighter (level responsive display)
  (if (cl-evenp level)
      'my-highlighter-even-face
    'my-highlighter-odd-face))

(setq highlight-indent-guides-highlighter-function 'my-highlighter)
```

It'll be more complicated if you also want to use the responsive feature (you can always look at the code for the [default highlighter](https://github.com/DarthFennec/highlight-indent-guides/blob/master/highlight-indent-guides.el#L572) as a reference if you want to do something like that). Let me know if you need any more help with this. Thanks!

**Comment by WeissP** [comment]
Thanks! Solved : )
