### ISSUE TITLE
Cursor disappears in emacs27

### ISSUE THREAD

**Issue by wedens** [DarthFennec/highlight-indent-guides#66]
With some recent changes in emacs27, when `highlight-indent-guides-method` is set to `character` and `hl-line-mode` is active, cursor disappears when typing. It doesn't happen with other `highlight-indent-guides-method` or if `hl-line-mode` is disabled.

It's probably related to some overlays/faces changes. (for example https://github.com/hlissner/emacs-doom-themes/issues/342 https://www.reddit.com/r/emacs/comments/diahh1/emacs_27_update_changed_how_highlighted_lines/). And this new default is unlikely to be reverted (see https://lists.gnu.org/archive/html/bug-gnu-emacs/2019-10/msg01809.html).

Setting `(custom-set-faces '(hl-line ((t (:extend t)))))` doesn't help.

I'm not really sure where this problem should be fixed.

**Comment by DarthFennec** [comment]
Wow, they really made that change? I feel like this will break *everything* ... oh well, I guess ...

It seems weird that this would be tied to `character` specifically, I'm not sure what's so different about that one as opposed to the others. Perhaps it's the use of the `display` property ... have you tried using `column` in a file with tab indents, rather than spaces? If `display` is the problem, then that should also trigger this issue.

I'll try to take a look at this soon, but right now I'm stuck in Emacs 26.3. When I find the time to upgrade, I'll look into it and let you know what I find.

**Comment by jcs090218** [comment]
I have encountered this issue too. Hope this get resolved ASAP! :(

**Comment by wedens** [comment]
Btw, it works fine with emacs 5a3e96b17c2a948ac952295962dc6e281ec5cad5 and some recent revision of doom-themes. But AFAIK there was some other change in more recent emacs revisions that may fix this problem in more cases (or break it further?).

**Comment by jcs090218** [comment]
@wedens Thanks for the update, I had been checking some threads and commits over past few hours. It seems like is an Emacs bug therefore hopefully they will fix this. :(

**Comment by jcs090218** [comment]
I think this can be closed. I have downloaded `27.0.60` and it resolved. :heart_eyes:

**Comment by wedens** [comment]
http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=58fb4c3e68a4a42ad491d0fa2c084e5c39942e2b this is the commit that should preserve backwards compatibility, I think.

**Comment by DarthFennec** [comment]
Awesome, glad it's working properly again.
