### ISSUE TITLE
Error on trying to disabling highlight-indent-guides-mode

### ISSUE THREAD

**Issue by CSRaghunandan** [DarthFennec/highlight-indent-guides#8]
Everything works fine till I try to disable `highlight-indent-guides-mode` and boom, it blows up on my face with an error: `(wrong-type-argument listp font-lock-extra-managed-props)` and I cant disable the minor mode.

I recently updated to emacs master build (started using this since it solves the annoying flickering issue emacs had on mac). Would this be the reason why it throws an error?

This is what I get when I enabled toggle debug on error:
```
Debugger entered--Lisp error: (wrong-type-argument listp font-lock-extra-managed-props)
  delete(display font-lock-extra-managed-props)
  (if highlight-indent-guides-mode (progn (add-to-list (quote font-lock-extra-managed-props) (quote display)) (font-lock-add-keywords nil (cond ((eq highlight-indent-guides-method (quote fill)) (let nil fill-method-keywords)) ((eq highlight-indent-guides-method (quote column)) (let nil column-method-keywords)) ((eq highlight-indent-guides-method (quote character)) (let nil character-method-keywords)) (t nil))) (jit-lock-register (quote highlight-indent-guides--guide-region))) (delete (quote display) (quote font-lock-extra-managed-props)) (font-lock-remove-keywords nil fill-method-keywords) (font-lock-remove-keywords nil column-method-keywords) (font-lock-remove-keywords nil character-method-keywords) (jit-lock-unregister (quote highlight-indent-guides--guide-region)) (highlight-indent-guides--unguide-region (point-min) (point-max)) (font-lock-flush))
  (let ((fill-method-keywords (quote ((highlight-indent-guides--fill-keyword-matcher 0 (highlight-indent-guides--fill-highlighter) t)))) (column-method-keywords (quote ((highlight-indent-guides--column-keyword-matcher 0 (highlight-indent-guides--column-highlighter) t)))) (character-method-keywords (quote ((highlight-indent-guides--column-keyword-matcher 0 (highlight-indent-guides--character-highlighter) t))))) (if highlight-indent-guides-mode (progn (add-to-list (quote font-lock-extra-managed-props) (quote display)) (font-lock-add-keywords nil (cond ((eq highlight-indent-guides-method (quote fill)) (let nil fill-method-keywords)) ((eq highlight-indent-guides-method (quote column)) (let nil column-method-keywords)) ((eq highlight-indent-guides-method (quote character)) (let nil character-method-keywords)) (t nil))) (jit-lock-register (quote highlight-indent-guides--guide-region))) (delete (quote display) (quote font-lock-extra-managed-props)) (font-lock-remove-keywords nil fill-method-keywords) (font-lock-remove-keywords nil column-method-keywords) (font-lock-remove-keywords nil character-method-keywords) (jit-lock-unregister (quote highlight-indent-guides--guide-region)) (highlight-indent-guides--unguide-region (point-min) (point-max)) (font-lock-flush)))
  (let ((last-message (current-message))) (setq highlight-indent-guides-mode (if (eq arg (quote toggle)) (not highlight-indent-guides-mode) (> (prefix-numeric-value arg) 0))) (let ((fill-method-keywords (quote ((highlight-indent-guides--fill-keyword-matcher 0 (highlight-indent-guides--fill-highlighter) t)))) (column-method-keywords (quote ((highlight-indent-guides--column-keyword-matcher 0 (highlight-indent-guides--column-highlighter) t)))) (character-method-keywords (quote ((highlight-indent-guides--column-keyword-matcher 0 (highlight-indent-guides--character-highlighter) t))))) (if highlight-indent-guides-mode (progn (add-to-list (quote font-lock-extra-managed-props) (quote display)) (font-lock-add-keywords nil (cond ((eq highlight-indent-guides-method ...) (let nil fill-method-keywords)) ((eq highlight-indent-guides-method ...) (let nil column-method-keywords)) ((eq highlight-indent-guides-method ...) (let nil character-method-keywords)) (t nil))) (jit-lock-register (quote highlight-indent-guides--guide-region))) (delete (quote display) (quote font-lock-extra-managed-props)) (font-lock-remove-keywords nil fill-method-keywords) (font-lock-remove-keywords nil column-method-keywords) (font-lock-remove-keywords nil character-method-keywords) (jit-lock-unregister (quote highlight-indent-guides--guide-region)) (highlight-indent-guides--unguide-region (point-min) (point-max)) (font-lock-flush))) (run-hooks (quote highlight-indent-guides-mode-hook) (if highlight-indent-guides-mode (quote highlight-indent-guides-mode-on-hook) (quote highlight-indent-guides-mode-off-hook))) (if (called-interactively-p (quote any)) (progn nil (if (and (current-message) (not (equal last-message (current-message)))) nil (let ((local " in current buffer")) (message "Highlight-Indent-Guides mode %sabled%s" (if highlight-indent-guides-mode "en" "dis") local))))))
  highlight-indent-guides-mode(toggle)
  funcall-interactively(highlight-indent-guides-mode toggle)
  call-interactively(highlight-indent-guides-mode record nil)
  command-execute(highlight-indent-guides-mode record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("highlight-indent-guides-mode")
  ivy-call()
  ivy-read("M-x " ("highlight-indent-guides-mode" "erc" "toggle-debug-on-error" "kill-emacs" "flycheck-mode" "shell" "magit-ediff-compare" "list-packages" "counsel-colors-emacs" "package-delete" "counsel-faces" "company-mode" "package-install" "eval-buffer" "counsel-rg" "counsel-describe-face" "customize-face" "customize-group" "recentf-cleanup" "server-force-delete" "spaceline-compile" "package-autoremove" "goto-address-mode" "counsel-colors-web" "counsel-mode" "ivy-push-view" "read-color" "flycheck-select-checker" "counsel-ag" "org-version" "company-complete" "hungry-delete-mode" "global-hl-line-mode" "projectile-purge-dir-from-cache" "term" "hl-line-mode" "rainbow-mode" "sunrise-sunset" "counsel-load-theme" "eval-print-last-sexp" "wdired-change-to-wdired-mode" "info" "woman" "swiper" "c++-mode" "org-goto" "winner-mode" "erase-buffer" "server-start" "erc-fill-mode" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
```

**Comment by DarthFennec** [comment]
Hmm ... so, `font-lock-extra-managed-props` is a variable that contains extra text properties that are managed by `font-lock`. Since `highlight-indent-guides` uses `font-lock`, and also uses the `display` text property of the whitespace it touches, it puts `display` in that list when it starts. That way, `font-lock` will know to include `display` as part of its fontification process. Then when you disable the mode, it removes `display` from the list. This is the part of the code that seems to be complaining:

``` emacs-lisp
(delete 'display 'font-lock-extra-managed-props)
```

As to why it's breaking, it seems that `delete` is complaining that `font-lock-extra-managed-props` is not a list (it does not pass `listp`). Which is strange because that variable should be a list, as far as I know. I can't reproduce this in my emacs, but I haven't tried the master build, so that might be the cause. Maybe they changed how that variable works?

If I were you, I'd try to see what the type/value actually is, to see whether that is in fact the issue. Something like:

``` emacs-lisp
C-h v font-lock-extra-managed-props RET
```

should do the trick, and then see what it says the current value is, and if there's anything of interest in the documentation. Beyond that, I have no idea. I feel like it should work fine, especially since when the plugin loads I run `add-to-list` on the same variable, and that's apparently working fine for you? I'd expect if it wasn't a list, `add-to-list` would complain as well.

**Comment by CSRaghunandan** [comment]
I managed to solve the error. I changed the erroneous line to: `(delete 'display font-lock-extra-managed-props)` and now I can disable `highlight-indent-guides-mode` without resulting in any errors.

Maybe new emacs master build changed the way `delete` is defined? I only know enough elisp to change/add things to my emacs config.

This is how `delete` function is defined in emacs master build:

> delete is a built-in function in ‘C source code’.
> 
> (delete ELT SEQ)
> 
> Delete members of SEQ which are ‘equal’ to ELT, and return the result.
> SEQ must be a sequence (i.e. a list, a vector, or a string).
> The return value is a sequence of the same type.
> 
>
> If SEQ is a list, this behaves like ‘delq’, except that it compares
> with ‘equal’ instead of ‘eq’.  In particular, it may remove elements
> by altering the list structure.
> 
> If SEQ is not a list, deletion is never performed destructively;
> instead this function creates and returns a new vector or string.
> 
> Write ‘(setq foo (delete element foo))’ to be sure of correctly
> changing the value of a sequence ‘foo’.
> 
> [back]
> 

Is that any different to how it is defined in the stable release? If there was a change it would have been mentioned right?

**Comment by DarthFennec** [comment]
Ah, that does make sense. When I use `add-to-list` earlier in the code, it takes the list to modify as a quoted name, so I assumed `delete` worked the same way ... but it seems that's incorrect. The difference between our emacs versions seems to be that in mine, it just fails silently ... but it fails either way. The list isn't actually being modified.

As it turns out, it doesn't get modified when I use your fix either; it avoids the error by passing the correct type, but it still does nothing. The only thing I've found that works (as suggested by the documentation) is:

``` emacs-lisp
(setq font-lock-extra-managed-props (delete 'display font-lock-extra-managed-props))
```

The problem with this is, now the `display` properties never get deleted because `font-lock` stops managing them, so there are just vertical lines everywhere that won't go away. Oddly, this still happens even when I move the delete to the end of the function, after the `font-lock-flush` call ... and I'm really not sure why ...

Considering that this delete call has apparently never actually done anything, it might make the most sense to just remove it entirely, and allow `font-lock` to manage `display` regardless of whether the plugin is enabled. For now I've just done that.

**Comment by CSRaghunandan** [comment]
Cool. Thanks for the quick fix

Also, concurrency branch has been merged into master apparently. Would you be able to use it to make this package faster if possible??

**Comment by DarthFennec** [comment]
I haven't been able to find much information on the concurrency branch, but maybe I'm just looking in the wrong places. The little I've been able to find makes it seem like it's a non-parallel cooperative style concurrency, basically a coroutine implementation. Is that right?

If that's the case, I doubt it'll help much for this mode. The point of using coroutines is that it allows you to break your execution up into smaller pieces, which just lets the UI run more often, so it doesn't hang while your code is running. But `font-lock` already does that for me, so it's not much of an issue. Of course, I'm sure I could use coroutines to make things run a little more smoothly, but for the most part `font-lock` handles this already. I'll definitely still look into it, since there might be something useful I can get out of it. But at the moment, I have no particular plans to use it. We'll see, though.
