### ISSUE TITLE
In TUI: `default' face is not set properly

### ISSUE THREAD

**Issue by laishulu** [DarthFennec/highlight-indent-guides#83]
When Emacs runs with TUI, I got 
```
Error: highlight-indent-guides cannot auto set faces: `default' face is not set properly
```
The problem does not exist in GUI Emacs.

https://github.com/hlissner/doom-emacs/blob/develop/modules/ui/indent-guides/config.el

**Comment by DarthFennec** [comment]
Weird, it works fine for me (and the issue mentioned in your link isn't a problem for me either, it sets the colors just fine without that hack). I've seen this error a few times, notably in issue #18 and #32. Let me know:

- What is the value of your `$TERM` environment variable? If this isn't `xterm-256color` or similar, that might be causing this error; your terminal might not think it supports the kind of color display necessary for this to work.
- Are you running emacs in a client/daemon configuration? Running emacs as a daemon used to cause this to happen. I fixed the issue then, but even so this might be a factor, It's always possible that I may have overlooked something.
- It's possible that you have another config or mode somewhere that's interfering. I've seen a situation where someone was getting this error because an unrelated mode had set an advice that created some kind of conflict. If possible, try running a clean emacs with just `highlight-indent-guides` enabled, to see if you still get the issue.

If nothing helps, you can always set the colors manually instead of depending on the automatic color selection:

``` elisp
(require 'highlight-indent-guides)

(setq highlight-indent-guides-auto-enabled nil)

(set-face-foreground 'highlight-indent-guides-character-face "color1")
(set-face-foreground 'highlight-indent-guides-top-character-face "color2")
(set-face-foreground 'highlight-indent-guides-stack-character-face "color3")
```

**Comment by laishulu** [comment]
- `echo $TERM` get `screen-256color`
- not `client/daemon`, just standalone emacs.
- a clean `init.el` with only melpa gives the same result.

**Comment by DarthFennec** [comment]
Hm ... after playing around with it, the only way I get that error is if I run emacs under `screen` and use the default value `TERM=screen`. When I set it to `screen-256color` I don't get the error, although the highlighting is messed up and I get very few colors. If I use `tmux` instead, it works entirely as expected, same as if I run it directly in the terminal. So I'm really lost as to what's going on on your end.

If I discover anything new about this, I'll let you know. Otherwise, it might be best to just set the colors manually, as I've described above.

**Comment by laishulu** [comment]
I run `Emacs Mac Port` in `MacOS Catalina`.
I don't know whether its the reason.

**Comment by laishulu** [comment]
But everything displays properly.
So, can you suppress the message?
It's annoying, and make the user suspect that something REALLY wrong happens.

<img width="674" alt="图片" src="https://user-images.githubusercontent.com/1224321/83091023-c4939400-a0cc-11ea-8eec-6c94bca16c8b.png">

**Comment by laishulu** [comment]
@DarthFennec 
But everything displays properly.
So, can you suppress the message?
It's annoying, and make the user suspect that something REALLY wrong happens.

<img width="678" alt="图片" src="https://user-images.githubusercontent.com/1224321/83091216-4683bd00-a0cd-11ea-92ab-bbbf347e24d6.png">

**Comment by DarthFennec** [comment]
>I run Emacs Mac Port in MacOS Catalina.
>Don't know whether its the reason.

I think that's what I'm using (I installed with `brew cask install emacs-mac`, I'm not positive about which build that is though). I doubt this is causing it, but it's always a possibility.

>But everything displays properly.

Got it, that changes things. I had thought it failed to set the highlight colors ... perhaps it's running twice for some reason, so it fails the first time and succeeds the second time? I don't know. As long as it's working as expected though, I could toss in a variable that suppresses the error, sure.

**Comment by laishulu** [comment]
Simple print：

<img width="621" alt="图片" src="https://user-images.githubusercontent.com/1224321/83173824-0a437180-a14c-11ea-8aa2-d34fe61e05b6.png">

Output：
<img width="756" alt="图片" src="https://user-images.githubusercontent.com/1224321/83173727-ec760c80-a14b-11ea-8c24-7c58ba84a88c.png">

**Comment by laishulu** [comment]
Simple print：

<img width="591" alt="图片" src="https://user-images.githubusercontent.com/1224321/83174091-76be7080-a14c-11ea-9dc3-4f3cfa2f3e23.png">

Output：

<img width="743" alt="图片" src="https://user-images.githubusercontent.com/1224321/83174067-673f2780-a14c-11ea-88c2-d08e80f5d5f6.png">

**Comment by DarthFennec** [comment]
So then I guess it does happen twice. Not sure why that is, but I guess it doesn't matter. I added a new flag to suppress the error:

``` emacs-lisp
(setq highlight-indent-guides-suppress-auto-error t)
```
