### ISSUE TITLE
Publish to Melpa-stable:

### ISSUE THREAD

**Issue by damon-kwok** [DarthFennec/highlight-indent-guides#86]
The method of execution:
```sh
cd highlight-indent-guides
git pull
git tag 0.0.1
git push origin 0.0.1
```
`Melpa` will soon find your new tag: 0.0.1, and then it will appear in `Melpa stable`.

**Comment by DarthFennec** [comment]
As discussed in issue #37, I don't see a need to release on MELPA stable at this point.

**Comment by damon-kwok** [comment]
If another package needs to reference highlight-indent-guides, the version number needs to be filled in. This version number can only be obtained from `melpa-stable`, so I am troubled by this problem

**Comment by DarthFennec** [comment]
I'm not really sure why another package would need to reference `highlight-indent-guides`, it's not really designed as a library for other packages to use or anything like that. Do you have a specific example of this so that maybe I can understand better?

I wasn't aware that packages need to be in Melpa Stable to be dependencies, if that's true then it's a good reason to consider this. It seems to me that you could just depend on the date-based version, but even if that's possible I can see why you might not want to.

**Comment by damon-kwok** [comment]
@DarthFennec 
Sess: https://github.com/ponylang/ponylang-mode/blob/master/ponylang-mode.el
I am planning to add highlight-indent-guide support to ponylang-mode. It has been released to melpa-stable, so all my dependencies must be on melpa-stable.

**Comment by DarthFennec** [comment]
I'm not so sure about this. `highlight-indent-guides` is a language-agnostic mode. If someone wants to use `highlight-indent-guides` in `ponylang-mode`, wouldn't they simply decide to install both? It's not like Pony benefits from this more than other languages, or uses it in a different way. If you'd like to recommend that people use this, I don't mind, but forcing it on people when they use some arbitrary major mode seems weird and unnecessary. Maybe it's just my personal bias, but I don't much like modes that try to do too much. I prefer modes that do just one thing, and then you can mix and match them as you see fit. The so-called Unix philosophy.

Feel free to disagree with me, I'm not telling you how to write your own code, but I just don't exactly see this as a viable tradeoff for me personally. I have little enough time to devote to this project as it is, so saying it's "unstable" and calling it a day beats spending even more time trying to make sure my tagged releases are "more stable" than my other commits (I generally try not to commit at all if the code doesn't seem stable enough). I could simply tag all my commits (I already version them all in a comment at the top of the file), but that would defeat the purpose of Melpa Stable so I really don't want to do that, it kind of feels like lying.

I don't have much in terms of automated tests yet, so it's difficult to gauge the stability of the code regardless, and because of that it's hard to promise that any release is necessarily "stable". I just feel like doing this would put needless extra pressure on me, and if it's for a reason that I don't think is all that important and don't really agree with, I don't feel so inclined to do it. Sorry.

**Comment by damon-kwok** [comment]
You're right.
