### ISSUE TITLE
Provide better support for themes

### ISSUE THREAD

**Issue by IvanMalison** [DarthFennec/highlight-indent-guides#9]
Though I definitely prefer highlight-indent-guides to highlight-indentation, I've found that the former is supported in far fewer themes than the latter.

Would you be open to providing an option to fall back to the faces provided by highlight-indentation (`highlight-indentation-current-column-face` and `highlight-indentation-face`) in highlight-indent-guides?

Doing this presents two (solvable, I think) problems:

1. There would need to be some way to determine whether the active theme has or has not set a face for highlight-indent-guides.
2. The highlight-indentation faces don't map EXACTLY to the highlight-indent-guides faces.

I think 2 can pretty much be ignored, since having themed faces is probably better than not, all things being equal, and we can simply choose a random assignment of the highlight-indentation faces to the highlight-indent-guides faces.

I can envision a few solutions to problem 1, but here is one that I think might work.

- offer a variable that controls whether or not fallback should happen
- Set the highlight-indent-guides faces to a sentinel value by default
- Have separate `highlight-indent-guides-odd-face-default` `highlight-indent-guides-even-face-default` faces for the purpose of this fallback, which will be the faces used when there are no highlight-indent-guides or highlight-indentation faces set.

**Comment by IvanMalison** [comment]
Random aside: based on your github avatar I suspect that we have super similar setups. Arch/(XMonad/Haskell)/Emacs masterrace!

**Comment by IvanMalison** [comment]
I suppose that you can also do something like

``` emacs-lisp
(defun after-load-theme (&rest _args)
  ;; Copy faces from highlight-indentation for highlight-indentation-guides
  (set-face-background 'highlight-indent-guides-even-face
                       (face-background 'highlight-indentation-face))
  (set-face-background 'highlight-indent-guides-odd-face
                       (face-background
                        'highlight-indentation-current-column-face)))

(advice-add 'load-theme :after 'after-load-theme)
```

**Comment by DarthFennec** [comment]
Well, the idea is that the user would specify the faces that work best in their theme. I had to pick a default, so I just picked the colors I personally use, but you're really supposed to customize it and set it to something that looks good to you. But you're right, having a default that looks okay in any theme is probably a good idea.

There are a few issues with using the faces from `highlight-indentation`:

- As you mentioned, not all themes have presets for the `highlight-indentation` faces. Although, if a theme supports an indent guide mode, it'll be that one, but even some of the most popular themes don't have that support. So there would need to be some sort of default or fallback.
- `highlight-indentation` itself specifies the default for the primary face to be `fringe`, and the secondary face to be black. I could use those if the theme doesn't specify defaults, but to me that doesn't seem any better than the current defaults: black is just a bad default color, and as far as I can tell, most popular themes use the background color for `fringe`, so you wouldn't be able to see the guides at all.
- From what I've seen, most of the themes that support `highlight-indentation` set the primary and secondary faces to the same color. This would work fine with the `'column` display method, but not the `'fill` method: this would just color all leading whitespace the same.

Outside of using `highlight-indentation`, the obvious thing to do is to try and find unrelated faces that are standard in emacs and would generally give okay-looking results in most themes, but that just opens up a whole other can of worms that I don't want to bother with.

A more radical solution is to dynamically generate the colors based on the current background color. This is what [`vim-indent-guides`](https://github.com/nathanaelkane/vim-indent-guides) does, and it's really cool. It would go something like this:

- Advise `load-theme`, as you suggested.
- Get the current background color from the `default` face.
- Use a heuristic to decide whether the theme is dark or light, depending on the background color. I'm thinking the heuristic should be "compare the intensity of `default:background` with that of `default:foreground`", since by definition a light theme is dark text on a lighter background, and a dark theme is light text on a darker background.
- Modify the color value by making it some percent lighter or darker, depending on whether the theme is dark or light, respectively. This is the primary color. Do it again with a different percentage for the secondary color.
- Set the new colors to the faces.

I expect this is what most people really want: colors that blend into their background, but are still visible against it. The percentages should probably be customizable, so you can tune the subtlety, and of course you should be able to turn this off and specify faces manually. But as far as defaults go, I think this is a solid approach. It would look correct in all themes, supported or not, and it wouldn't require any configuration. It probably wouldn't be too hard to implement, as well ...

**Comment by IvanMalison** [comment]
I wrote the following which does roughly what you said, though it doesnt really handle any of the fallbacks yet. I'll make a pull request if you like the approach

``` emacs-lisp
(defun imalison:change-hsv-value-by (delta)
  (lambda (h s v)
    (list h s (+ v delta))))

(defun imalison:build-safe-change-hsv-value (delta)
  (lambda (h s v)
    (imalison:safe-change-hsv-value
     h s v delta)))

(defun imalison:new-hsv-value-safe (value)
  (or (> value 1) (< value 0)))

(defun imalison:safe-change-hsv-value (h s v delta)
  (let ((new-value (+ v delta)))
    (if (imalison:new-hsv-value-safe new-value)
        (let ((other-direction (+ v (* delta -2))))
          (if (imalison:new-hsv-value-safe other-direction)
              (user-error "delta %s is too large" delta)
            (list h s other-direction)))
      (list h s new-value))))

(defun imalison:modify-hsv (color fn)
  (hexrgb-rgb-hex-to-rgb-hex
   (apply 'hexrgb-hsv-to-hex (apply fn (hexrgb-hex-to-hsv color))) 2))

(defun imalison:modify-hsv-value-by (color delta)
  (imalison:modify-hsv color (imalison:build-safe-change-hsv-value delta)))

(defvar imalison:hsv-value-delta .03)

(defun imalison:set-highlight-indent-guides-faces ()
  (interactive)
  (let ((bg-color (face-background 'default)))
    (set-face-background 'highlight-indent-guides-odd-face
                         (imalison:modify-hsv
                          bg-color
                          (imalison:build-safe-change-hsv-value
                           (* -1 imalison:hsv-value-delta))))
    (set-face-background 'highlight-indent-guides-even-face
                         (imalison:modify-hsv
                          bg-color
                          (imalison:build-safe-change-hsv-value
                           imalison:hsv-value-delta)))))
```

**Comment by IvanMalison** [comment]
I had to add this really nasty hack to make the advice to load-them work because

(face-background 'default) is nil after `load-theme` is called. Not sure what is going on there. My guess is that at some point load-theme relies on a callback somewhere or something, so the value is not properly set.

```
;; XXX: This hacks around the fact that (face-background 'default) is nil at
;; the time of load-theme
(defun imalison:set-highlight-indent-guides-faces-load-theme (&rest args)
  (if (face-background 'default)
      (imalison:set-highlight-indent-guides-faces)
    (run-at-time "1 sec" nil 'imalison:set-highlight-indent-guides-faces-load-theme)))

(advice-add 'load-theme
            :after 'imalison:set-highlight-indent-guides-faces-load-theme)
```

**Comment by DarthFennec** [comment]
I went and wrote it today, you can pull the latest commit and see if it works for you. It looks great for all the themes I've tried so far, anyway. Strangely, I didn't need the sleep hack, I'm not really sure why you do ... I looked around in `load-theme` and I couldn't find any callback shenanigans, so I don't know ... I guess, let me know if you still have that problem with my code, and we can go from there.

**Comment by IvanMalison** [comment]
Turns out the load-theme thing had to do with an issue in advice I had added to eval-last-defun for the package eros. Still not sure how that caused this, but it did.

Your solution seems pretty nice. Closing.
