### ISSUE TITLE
Tab Chars Displayed With >

### ISSUE THREAD

**Issue by qazxwecvr** [DarthFennec/highlight-indent-guides#98]
I don't know if this is intentional, but if it is, I would like to disable it.
When the indent guides are enabled, tabs are not displayed with a line. Instead, they are displayed like:
![image](https://user-images.githubusercontent.com/56793761/89240262-de63c280-d5b8-11ea-9aed-967d03c429e1.png)

**Comment by DarthFennec** [comment]
I've never seen that before. First, just to be sure, I'd check the value of `highlight-indent-guides-character` and make sure that's not the culprit. Beyond that, it might be that some other mode is interfering (like `whitespace` or something), so check if this still happens when you run a clean Emacs, with nothing loaded other than `highlight-indent-guides`. Does this just happen when using the `character` method, or are `fill` and `column` also affected?

**Comment by qazxwecvr** [comment]
You're right it was just the white-space mode. I had completely forgotten about it! :D Sorry to waste your time with something so small and easily fixable, but thank you.
